2017-08-18 10:56:36 WARNING (MainThread) [homeassistant.setup] Setup of notify is taking over 10 seconds.
2017-08-18 10:56:37 WARNING (MainThread) [homeassistant.setup] Setup of sensor is taking over 10 seconds.
2017-08-18 10:56:37 WARNING (MainThread) [homeassistant.setup] Setup of media_player is taking over 10 seconds.
2017-08-18 10:56:38 WARNING (MainThread) [homeassistant.setup] Setup of device_tracker is taking over 10 seconds.
2017-08-18 10:56:40 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform fitbit
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 164, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 372, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/sensor/fitbit.py", line 249, in setup_platform
    authd_client.client.refresh_token()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/fitbit/api.py", line 163, in refresh_token
    auth=requests.auth.HTTPBasicAuth(self.client_id, self.client_secret)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
2017-08-18 10:56:53 WARNING (MainThread) [homeassistant.components.sensor.template] Could not render template Thermostat Battery, the state is unknown.
2017-08-18 10:56:55 WARNING (MainThread) [homeassistant.helpers.condition] Value cannot be processed as a number: 
2017-08-18 10:57:16 WARNING (Thread-8) [netdisco.ssdp] Found malformed XML at http://192.168.88.18:9080: status=ok
2017-08-18 10:57:23 WARNING (Thread-9) [homeassistant.components.zwave] zwave not ready after 30 seconds, continuing anyway
2017-08-18 10:58:28 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 10:58:38 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 10:58:38 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 10:58:38 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 10:58:38 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 10:58:49 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:00:28 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:00:28 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:00:28 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:00:28 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:08 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:18 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:18 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:18 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:18 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:51 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='192.168.88.20', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:51 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:51 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:51 WARNING (Thread-9) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:51 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:51 WARNING (Thread-9) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:51 WARNING (Thread-9) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:51 WARNING (Thread-9) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:58 WARNING (Thread-7) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:58 WARNING (Thread-7) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:58 WARNING (Thread-7) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:02:58 WARNING (Thread-7) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:03:02 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:03:02 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:03:02 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:03:02 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:03:58 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:04:08 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:04:08 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:04:08 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:04:08 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:05:48 WARNING (Thread-5) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:05:58 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:05:58 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:05:58 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:05:58 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:07:38 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:07:48 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:07:48 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:07:48 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:07:48 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:09:28 WARNING (Thread-5) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:09:38 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:09:38 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:09:38 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:09:38 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:11:28 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:11:28 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:11:28 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:11:28 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:13:18 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:13:18 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:13:18 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:13:18 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:14:58 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:15:08 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:15:08 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:15:08 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:15:08 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:16:48 WARNING (Thread-5) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:16:58 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:16:58 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:16:58 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:16:58 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:17:57 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2017-08-18 11:18:38 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:18:48 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:18:48 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:18:48 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:18:48 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:20:28 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:20:38 WARNING (Thread-9) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:20:38 WARNING (Thread-9) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:20:38 WARNING (Thread-9) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:20:38 WARNING (Thread-9) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:22:18 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:22:28 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:22:28 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:22:28 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:22:28 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:24:08 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:24:08 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:24:18 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:24:18 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:24:18 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:24:18 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:24:31 WARNING (Thread-11) [netdisco.ssdp] Error fetching description at http://192.168.88.22:2869/upnphost/udhisapi.dll?content=uuid:b0611f8b-d39a-4ba4-bd02-c7e7479ffd35
2017-08-18 11:25:58 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:26:08 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:26:08 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:26:08 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:26:09 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:27:48 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:27:58 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:27:58 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:27:59 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:27:59 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:29:38 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:29:48 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:29:48 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:29:49 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-08-18 11:29:49 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
